# Generated by Django 4.2.7 on 2024-01-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(default=None, max_length=225, verbose_name="Email"),
        ),
    ]
