# Generated by Django 4.2.7 on 2024-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=225, null=True, verbose_name="Email"
            ),
        ),
    ]
