# Generated by Django 4.2.7 on 2023-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salemodel",
            name="products",
            field=models.JSONField(default=None, null=True, verbose_name="Products"),
        ),
    ]
